### PR TITLE
Feat/javid hassani

### PR DESCRIPTION
**Pull request by Javidleo**
##  Summary
adding dotnet project structure via **dotnet-cli**

## Added
- adding console application template 
- adding webapi application template
- adding classlib template
- adding xunit test project for each one above
- adding fluent assertion package to each xunit test project
- create readme file for my projects

### CODE REVIEW

**Comment by Javidleo** [comment]
sorry for separate the job in different more than one commit.
I forgot to push some changes twice.

**Comment by thisisnabi** [comment]
Please move source projects into the `src` folder.

**Comment by thisisnabi** [comment]
Do you want to do the tool project?

**Comment by Javidleo** [comment]
> Do you want to do the tool project?

Yes I will finish it before 2 pm

**Review by thisisnabi — APPROVED** [review]

**Pull request merged**
